version: '3'

services:
  back:
    build: .
    container_name: api
    ports:
      - 3000:3000
    working_dir: /back-app
    tty: true
    stdin_open: true
    command: npm run start:dev
    volumes:
      - ./back-app:/back-app
    depends_on:
      - postgres_db
    environment:
      PORT: 3000
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: postgres_db
    restart: always
